### ISSUE TITLE
Build from Github Actions isn't reobfuscated

### ISSUE THREAD

**Issue by mcmdev** [Trigary/Iodine#26] opened 2020-03-05 16:13 UTC
I'm not entirely sure if it's intentional but the build from the Github Actions tab isn't reobfuscated which crashes the client when joining a server

**Comment by Trigary** [comment] 2020-03-05 17:37
Thank you for taking interesting in this project and reporting this bug. That was definitely not intentional. The problem was that I did `gradlew jar` instead of `gradlew build`. Confirmed to be fixed by add0ff8a3ab4644ee9edda61f10ab18dc0c607a3

**Closed as completed by Trigary** 2020-03-05 17:37 UTC
